<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>

    <NeutralLanguage>en</NeutralLanguage>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>CS1591</NoWarn>

    <RootNamespace>AvalonLog</RootNamespace>
    <AssemblyName>AvalonLog</AssemblyName>
    <AssemblyTitle>AvalonLog</AssemblyTitle>
    <Title>AvalonLog</Title>
    <Product>AvalonLog</Product>
    <PackageId>AvalonLog</PackageId>

    <Authors>GoswinR</Authors>
    <Copyright>Goswin Rothenthal 2021</Copyright>

    <PackageDescription>A fast and thread-safe WPF text viewer for colored text. Based on AvalonEdit</PackageDescription>
    <Description>A fast and thread-safe WPF text viewer for colored text. Based on AvalonEdit</Description>

    <PackageTags>wpf;console;csharp;avalonedit</PackageTags>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>logo128.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <DebugType>embedded</DebugType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <RepositoryUrl>https://github.com/goswinr/AvalonLog</RepositoryUrl>
    <ChangelogFile>../CHANGELOG.md</ChangelogFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEditB" Version="2.4.0" />
    <PackageReference Include="Ionide.KeepAChangelog.Tasks" Version="0.3.3" PrivateAssets="all" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.201" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" />
    <None Include="../Docs/img/logo128.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="WriteChangelogVersion" AfterTargets="AfterBuild">
    <WriteLinesToFile File="./bin/ChangelogVersion.txt" Lines="@(CurrentReleaseChangelog)" Overwrite="true" ContinueOnError="false" />
  </Target>

  <Target Name="CopyReadmeToDocs" AfterTargets="Build">
    <Copy SourceFiles="../README.md" DestinationFiles="../Docs/index.md" ContinueOnError="false" />
  </Target>
</Project>
